config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  resources :courts do
    collection do
      post :delete_all
    end
    member do
      post :add_worker
    end
  end

  resources :workers, :shifts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/court.rb
class Court < ApplicationRecord
  has_many :staffings
  has_many :active_staffings, -> { where(active: true) }, class_name: "Staffing"
  has_many :workers, through: :staffings
  has_many :active_workers, through: :active_staffings, class_name: "Worker", source: :worker
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :worker
  belongs_to :staffing

  before_validation :assign_worker, on: :create
  validates_presence_of :start_time
  before_save :assign_duration

  def assign_worker
    self.worker = staffing.worker
  end

  def assign_duration
    return if end_time.blank?
    return unless end_time_changed? || start_time_changed?
    self.duration = end_time - start_time
  end

  def formatted_duration
    "%02dh %02dm" % [duration/3600, duration/60%60, duration%60]
  end
end

app/models/staffing.rb
class Staffing < ApplicationRecord
  belongs_to :court
  belongs_to :worker
  has_many :shifts

  validates_uniqueness_of :worker, conditions: -> { where(active: true) }
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :staffings
  has_one :active_staffing, -> { where(active: true) }, class_name: "Staffing"
  has_many :courts, through: :staffings
  has_many :shifts, through: :staffings
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  around_action :set_default_time_zone

  def set_default_time_zone(&block)
    Time.use_zone("London", &block)
  end

end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  def index
    @courts = Court.all.order(:id)
  end

  def show
    @court = Court.find(params[:id])
  end

  def new
  end

  def create
    @court = Court.new(court_params)
    @court.save
    redirect_to @court
  end

  private
    def court_params
      params.require(:court).permit(:name, :staff_total)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @posts = Post.all.order(:id)
    @courts = Court.all.order(:id)
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def update
    @shift = Shift.find(params[:id])
    @shift.update(end_time: params[:end_time])
    redirect_to worker_path(@shift.worker)
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def index
    @workers = Worker.all.order(:id)
  end

  def show
    @worker = Worker.find(params[:id])
  end

  def new
    @worker = Worker.new
  end

  def edit
    @worker = Worker.find(params[:id])
    @assigned_court_id = @worker.active_staffing&.court_id
  end

  def update
    @worker = Worker.find(params[:id])
    if @worker.update(worker_params)
      if @worker.active_staffing
        @worker.active_staffing.update!(active: false)
      end
      @worker.staffings.create!(court_id: params[:assigned_court_id], active: true)
      redirect_to @worker
    else
      render 'edit'
    end
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      redirect_to @worker
    else
      render 'new'
    end
  end

  private
    def worker_params
      params.require(:worker).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/courts/index.html.haml
%h1 All Courts
%table.table.table-sm
  %tr
    %thead.thead-dark
      %th Court
      %th Total staff required
      %th
    %tbody
    - @courts.each do |court|
      %tr
        %td= court.name
        %td= court.staff_total
        %td= link_to 'Details', court_path(court)

app/views/courts/new.html.haml
%h1 Create Court
= form_with scope: :court, url: courts_path, local: true do |form|
  %p
    = form.label :name
    %br/
    = form.text_field :name
  %p
    = form.label :staff_total
    %br/
    = form.number_field :staff_total
  %p
    = form.submit

app/views/courts/show.html.haml
%p
  %strong Court Name:
  = @court.name
%p
  %strong Total staff required:
  = @court.staff_total
%p
  = link_to 'Home', root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wimb
    = csrf_meta_tags
    = csp_meta_tag
    %link{href: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", crossorigin: "anonymous"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %ul.navbar-nav.mr-auto
          %li.nav-item
            = link_to 'Home', root_path, class: "nav-link"
          %li.nav-item
            = link_to 'Courts', courts_path, class: "nav-link"
          %li.nav-item
            = link_to 'Workers', workers_path, class: "nav-link"
    %br
    = yield

app/views/main/index.html.haml
%h1 Dashboard
%table.table.table-sm
  %thead.thead-dark
    %tr
      %th Court
      %th Required staff
      %th Current staff
      %th Allocated staff
  %tbody
  - @courts.each do |court|
    %tr
      %td
        = court.name
      %td
        = court.staff_total
      %td
        = court.active_workers.count
      %td
        - court.active_workers.each do |worker|
          %p= link_to worker.name, worker_path(worker)

app/views/workers/edit.html.haml
%h1 Edit worker
= form_with model: @worker, local: true do |form|
  - if @worker.errors.any?
    %div#error_explanation
    %h2{:style => "color:red"} #{pluralize(@worker.errors.count, 'error')} prevented saving:
    %ul
      - @worker.errors.full_messages.each do |message|
        %li{:style => "color:red"}
          = message
  %p
    = form.label :name
    %br/
    = form.text_field :name

  %p
    Assigned court:
    = select_tag :assigned_court_id, options_from_collection_for_select(Court.all.order(:name), "id", "name", @assigned_court_id), include_blank: true
  %p
    = form.submit

%p
  = link_to 'Back', workers_path

app/views/workers/index.html.haml
%h1 All Workers
%table.table.table-sm
  %thead.thead-dark
    %tr
      %th Worker
      %th Court
  %tbody
    - @workers.each do |worker|
      %tr
        %td= link_to worker.name, worker_path(worker)
        - if worker.courts.first.present?
          %td= worker.courts.first.name
        - else
          %td= link_to 'Assign court', worker_path(worker)

app/views/workers/new.html.haml
%h1 Add new worker
= form_with scope: :worker, url: workers_path, local: true do |form|
  - if @worker.errors.any?
    %div#error_explanation
    %h2{:style => "color:red"} #{pluralize(@worker.errors.count, 'error')} prevented saving:
    %ul
      - @worker.errors.full_messages.each do |message|
        %li{:style => "color:red"}
          = message
  %p
    = form.label :name
    %br/
    = form.text_field :name
  %p
    = form.submit

app/views/workers/show.html.haml
%h1
  = @worker.name

%p
  = link_to 'Edit personal info', edit_worker_path(@worker)

%h3 Timesheet

- if @worker.shifts.present?
  %table.table.table-bordered
    %tr
      %th Location
      %th Start time
      %th End time
      %th Duration
      - @worker.shifts.each do |shift|
        %tr
          %td
            = shift.staffing.court.name
          %td
            = shift.start_time.to_s(:display_time_and_date)
          %td
            - if shift.end_time.present?
              = shift.end_time.to_s(:display_time_and_date)
            - else
              = link_to 'Sign out now', shift_path(shift, :end_time => Time.now), :method => :put
          %td
            - if !shift.duration.nil?
              = shift.formatted_duration
- else
  %p No shifts to display